### ISSUE TITLE
phpunit

### ISSUE THREAD

**Issue by erikfrerejean** [phpBB-Blog/phpBB-Blog-for-3.1#15]
Add the phpunit test core.

**Comment by michaelcullum** [comment]
Merged in #16

**Comment by michaelcullum** [comment]
Shouldn't this be closed?

**Comment by erikfrerejean** [comment]
Have you verified that local runs still work? I've been adjusting things for Travis, but haven't tested lical runs since. So please verify that before closing (testing using the `phpunit.dist.xml` configuration in the root.

**Comment by michaelcullum** [comment]
Ok, /me still need to work out how to use tests properly. :P
