### ISSUE TITLE
Travis-ci

### ISSUE THREAD

**Issue by erikfrerejean** [phpBB-Blog/phpBB-Blog-for-3.1#34]
Reminder for self. Look into db possibilities on travis. Might cause some issues where we rely on phpBB code.

**Comment by michaelcullum** [comment]
#30 #31 #32 #33 #35

**Comment by erikfrerejean** [comment]
http://travis-ci.org/#!/erikfrerejean/phpBB-Blog-for-3.1
I've got it to the point where everything besides the tests on `PHP 5.4` pass. For now I'd suggest dropping this and look at that later. `PHP 5.2` and `PHP 5.3` should be sufficient for now.

**Comment by michaelcullum** [comment]
Merge it yourself when your ready then.

**Comment by erikfrerejean** [comment]
Fixed in #36
