### ISSUE TITLE
Drop 5.2 support

### ISSUE THREAD

**Issue by michaelcullum** [phpBB-Blog/phpBB-Blog-for-3.1#67]
I'll make this as a ticket as a place to discuss it.

My proposal is to drop 5.2 support as we neither test against it, nor does 3.1 support it. The minimum php version requirement would be 5.3.2 or higher as per 3.1

**Comment by michaelcullum** [comment]
@erikfrerejean ;)

**Comment by erikfrerejean** [comment]
Still -1, until someone can bring up a feasible use case _(other then the not test/phpBB support discussion)_. And please don't come up with the theoretical gibberish that was thrown around before.
As stated in the past, I'm not against this per se. But I am against limitations for the sake of limitations.

**Comment by michaelcullum** [comment]
I'd have thought the fact that the script it relies on (phpBB) not supporting it would be a pretty big point. 

To be honest, I can see maybe 1 person using this on 5.2 due to the level of expertise needed to change phpbb to make it run on 5.2 and most people with that level of expertise will upgrade PHP? It would be less work for the user to upgrade than adjust phpBB to support 5.2 (not using namespaces, :? etc)

I don't see why we should use a piece of software that is now two feature releases out of date and has been EOL'd for quite a while we can base it on 5.3.2 with the difference of perhaps a single user, or we could make use of new technologies. 5.2 isn't even supported for security releases now I dont think.
