### ISSUE TITLE
Work out where we need ledges

### ISSUE THREAD

**Issue by michaelcullum** [phpBB-Blog/phpBB-Blog-for-3.1#8]
Work out where we need ledges (hook locations) so they can be requested. ;) Please reply with them in here.

**Comment by imkingdavid** [comment]
I can't think of any ledges we need, other than the page head one that is already there for adding links to the nav bar.

**Comment by michaelcullum** [comment]
They are called events now and yeah, I suppose. Possibly add a footer link too as a blog is a major feature? Both of which I've already added.
